// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package link

import "golang.design/x/nanogo/obj"

// builtins is the list of predeclared runtime symbols, in the order the
// object format numbers them.
//
// A reference to one of these is an index into this list and carries no
// name, so the list is part of the format and not a convenience. It is
// pinned the way obj.Magic is pinned: specs/040-object-format.md says a
// version mismatch is an error and not a negotiation, and
// TestBuiltinListMatchesTheToolchain compares this copy with the
// installed toolchain's.
//
// The ABI is part of the entry because the same name appears at both, and
// a reference resolves to one of them.
var builtins = [...]struct {
	name string
	abi  uint16
}{
	{"runtime.newobject", obj.ABIInternal},
	{"runtime.mallocgc", obj.ABIInternal},
	{"runtime.panicdivide", obj.ABIInternal},
	{"runtime.panicshift", obj.ABIInternal},
	{"runtime.panicmakeslicelen", obj.ABIInternal},
	{"runtime.panicmakeslicecap", obj.ABIInternal},
	{"runtime.throwinit", obj.ABIInternal},
	{"runtime.panicwrap", obj.ABIInternal},
	{"runtime.gopanic", obj.ABIInternal},
	{"runtime.gorecover", obj.ABIInternal},
	{"runtime.goschedguarded", obj.ABIInternal},
	{"runtime.goPanicIndex", obj.ABIInternal},
	{"runtime.goPanicIndexU", obj.ABIInternal},
	{"runtime.goPanicSliceAlen", obj.ABIInternal},
	{"runtime.goPanicSliceAlenU", obj.ABIInternal},
	{"runtime.goPanicSliceAcap", obj.ABIInternal},
	{"runtime.goPanicSliceAcapU", obj.ABIInternal},
	{"runtime.goPanicSliceB", obj.ABIInternal},
	{"runtime.goPanicSliceBU", obj.ABIInternal},
	{"runtime.goPanicSlice3Alen", obj.ABIInternal},
	{"runtime.goPanicSlice3AlenU", obj.ABIInternal},
	{"runtime.goPanicSlice3Acap", obj.ABIInternal},
	{"runtime.goPanicSlice3AcapU", obj.ABIInternal},
	{"runtime.goPanicSlice3B", obj.ABIInternal},
	{"runtime.goPanicSlice3BU", obj.ABIInternal},
	{"runtime.goPanicSlice3C", obj.ABIInternal},
	{"runtime.goPanicSlice3CU", obj.ABIInternal},
	{"runtime.goPanicSliceConvert", obj.ABIInternal},
	{"runtime.printbool", obj.ABIInternal},
	{"runtime.printfloat64", obj.ABIInternal},
	{"runtime.printfloat32", obj.ABIInternal},
	{"runtime.printint", obj.ABIInternal},
	{"runtime.printhex", obj.ABIInternal},
	{"runtime.printuint", obj.ABIInternal},
	{"runtime.printcomplex128", obj.ABIInternal},
	{"runtime.printcomplex64", obj.ABIInternal},
	{"runtime.printstring", obj.ABIInternal},
	{"runtime.printquoted", obj.ABIInternal},
	{"runtime.printpointer", obj.ABIInternal},
	{"runtime.printuintptr", obj.ABIInternal},
	{"runtime.printiface", obj.ABIInternal},
	{"runtime.printeface", obj.ABIInternal},
	{"runtime.printslice", obj.ABIInternal},
	{"runtime.printnl", obj.ABIInternal},
	{"runtime.printsp", obj.ABIInternal},
	{"runtime.printlock", obj.ABIInternal},
	{"runtime.printunlock", obj.ABIInternal},
	{"runtime.concatstring2", obj.ABIInternal},
	{"runtime.concatstring3", obj.ABIInternal},
	{"runtime.concatstring4", obj.ABIInternal},
	{"runtime.concatstring5", obj.ABIInternal},
	{"runtime.concatstrings", obj.ABIInternal},
	{"runtime.concatbyte2", obj.ABIInternal},
	{"runtime.concatbyte3", obj.ABIInternal},
	{"runtime.concatbyte4", obj.ABIInternal},
	{"runtime.concatbyte5", obj.ABIInternal},
	{"runtime.concatbytes", obj.ABIInternal},
	{"runtime.cmpstring", obj.ABIInternal},
	{"runtime.intstring", obj.ABIInternal},
	{"runtime.slicebytetostring", obj.ABIInternal},
	{"runtime.slicebytetostringtmp", obj.ABIInternal},
	{"runtime.slicerunetostring", obj.ABIInternal},
	{"runtime.stringtoslicebyte", obj.ABIInternal},
	{"runtime.stringtoslicerune", obj.ABIInternal},
	{"runtime.slicecopy", obj.ABIInternal},
	{"runtime.decoderune", obj.ABIInternal},
	{"runtime.countrunes", obj.ABIInternal},
	{"runtime.convT", obj.ABIInternal},
	{"runtime.convTnoptr", obj.ABIInternal},
	{"runtime.convT16", obj.ABIInternal},
	{"runtime.convT32", obj.ABIInternal},
	{"runtime.convT64", obj.ABIInternal},
	{"runtime.convTstring", obj.ABIInternal},
	{"runtime.convTslice", obj.ABIInternal},
	{"runtime.assertE2I", obj.ABIInternal},
	{"runtime.assertE2I2", obj.ABIInternal},
	{"runtime.panicdottypeE", obj.ABIInternal},
	{"runtime.panicdottypeI", obj.ABIInternal},
	{"runtime.panicnildottype", obj.ABIInternal},
	{"runtime.typeAssert", obj.ABIInternal},
	{"runtime.interfaceSwitch", obj.ABIInternal},
	{"runtime.ifaceeq", obj.ABIInternal},
	{"runtime.efaceeq", obj.ABIInternal},
	{"runtime.panicrangestate", obj.ABIInternal},
	{"runtime.deferrangefunc", obj.ABIInternal},
	{"runtime.rand", obj.ABIInternal},
	{"runtime.rand32", obj.ABIInternal},
	{"runtime.makemap64", obj.ABIInternal},
	{"runtime.makemap", obj.ABIInternal},
	{"runtime.makemap_small", obj.ABIInternal},
	{"runtime.mapaccess1", obj.ABIInternal},
	{"runtime.mapaccess1_fast32", obj.ABIInternal},
	{"runtime.mapaccess1_fast64", obj.ABIInternal},
	{"runtime.mapaccess1_faststr", obj.ABIInternal},
	{"runtime.mapaccess1_fat", obj.ABIInternal},
	{"runtime.mapaccess2", obj.ABIInternal},
	{"runtime.mapaccess2_fast32", obj.ABIInternal},
	{"runtime.mapaccess2_fast64", obj.ABIInternal},
	{"runtime.mapaccess2_faststr", obj.ABIInternal},
	{"runtime.mapaccess2_fat", obj.ABIInternal},
	{"runtime.mapassign", obj.ABIInternal},
	{"runtime.mapassign_fast32", obj.ABIInternal},
	{"runtime.mapassign_fast32ptr", obj.ABIInternal},
	{"runtime.mapassign_fast64", obj.ABIInternal},
	{"runtime.mapassign_fast64ptr", obj.ABIInternal},
	{"runtime.mapassign_faststr", obj.ABIInternal},
	{"runtime.mapIterStart", obj.ABIInternal},
	{"runtime.mapdelete", obj.ABIInternal},
	{"runtime.mapdelete_fast32", obj.ABIInternal},
	{"runtime.mapdelete_fast64", obj.ABIInternal},
	{"runtime.mapdelete_faststr", obj.ABIInternal},
	{"runtime.mapIterNext", obj.ABIInternal},
	{"runtime.mapclear", obj.ABIInternal},
	{"runtime.makechan64", obj.ABIInternal},
	{"runtime.makechan", obj.ABIInternal},
	{"runtime.chanrecv1", obj.ABIInternal},
	{"runtime.chanrecv2", obj.ABIInternal},
	{"runtime.chansend1", obj.ABIInternal},
	{"runtime.closechan", obj.ABIInternal},
	{"runtime.chanlen", obj.ABIInternal},
	{"runtime.chancap", obj.ABIInternal},
	{"runtime.writeBarrier", obj.ABI0},
	{"runtime.typedmemmove", obj.ABIInternal},
	{"runtime.typedmemclr", obj.ABIInternal},
	{"runtime.typedslicecopy", obj.ABIInternal},
	{"runtime.selectnbsend", obj.ABIInternal},
	{"runtime.selectnbrecv", obj.ABIInternal},
	{"runtime.selectsetpc", obj.ABIInternal},
	{"runtime.selectgo", obj.ABIInternal},
	{"runtime.block", obj.ABIInternal},
	{"runtime.makeslice", obj.ABIInternal},
	{"runtime.makeslice64", obj.ABIInternal},
	{"runtime.makeslicecopy", obj.ABIInternal},
	{"runtime.growslice", obj.ABIInternal},
	{"runtime.growsliceBuf", obj.ABIInternal},
	{"runtime.growsliceBufNoAlias", obj.ABIInternal},
	{"runtime.growsliceNoAlias", obj.ABIInternal},
	{"runtime.unsafeslicecheckptr", obj.ABIInternal},
	{"runtime.panicunsafeslicelen", obj.ABIInternal},
	{"runtime.panicunsafeslicenilptr", obj.ABIInternal},
	{"runtime.unsafestringcheckptr", obj.ABIInternal},
	{"runtime.panicunsafestringlen", obj.ABIInternal},
	{"runtime.panicunsafestringnilptr", obj.ABIInternal},
	{"runtime.moveSlice", obj.ABIInternal},
	{"runtime.moveSliceNoScan", obj.ABIInternal},
	{"runtime.moveSliceNoCap", obj.ABIInternal},
	{"runtime.moveSliceNoCapNoScan", obj.ABIInternal},
	{"runtime.memmove", obj.ABIInternal},
	{"runtime.memclrNoHeapPointers", obj.ABIInternal},
	{"runtime.memclrHasPointers", obj.ABIInternal},
	{"runtime.memequal", obj.ABIInternal},
	{"runtime.memequal0", obj.ABIInternal},
	{"runtime.memequal8", obj.ABIInternal},
	{"runtime.memequal16", obj.ABIInternal},
	{"runtime.memequal32", obj.ABIInternal},
	{"runtime.memequal64", obj.ABIInternal},
	{"runtime.memequal128", obj.ABIInternal},
	{"runtime.f32equal", obj.ABIInternal},
	{"runtime.f64equal", obj.ABIInternal},
	{"runtime.c64equal", obj.ABIInternal},
	{"runtime.c128equal", obj.ABIInternal},
	{"runtime.strequal", obj.ABIInternal},
	{"runtime.interequal", obj.ABIInternal},
	{"runtime.nilinterequal", obj.ABIInternal},
	{"runtime.memhash", obj.ABIInternal},
	{"runtime.memhash0", obj.ABIInternal},
	{"runtime.memhash8", obj.ABIInternal},
	{"runtime.memhash16", obj.ABIInternal},
	{"runtime.memhash32", obj.ABIInternal},
	{"runtime.memhash64", obj.ABIInternal},
	{"runtime.memhash128", obj.ABIInternal},
	{"runtime.f32hash", obj.ABIInternal},
	{"runtime.f64hash", obj.ABIInternal},
	{"runtime.c64hash", obj.ABIInternal},
	{"runtime.c128hash", obj.ABIInternal},
	{"runtime.strhash", obj.ABIInternal},
	{"runtime.interhash", obj.ABIInternal},
	{"runtime.nilinterhash", obj.ABIInternal},
	{"runtime.int64div", obj.ABIInternal},
	{"runtime.uint64div", obj.ABIInternal},
	{"runtime.int64mod", obj.ABIInternal},
	{"runtime.uint64mod", obj.ABIInternal},
	{"runtime.float64toint64", obj.ABIInternal},
	{"runtime.float64touint64", obj.ABIInternal},
	{"runtime.float64touint32", obj.ABIInternal},
	{"runtime.int64tofloat64", obj.ABIInternal},
	{"runtime.int64tofloat32", obj.ABIInternal},
	{"runtime.uint64tofloat64", obj.ABIInternal},
	{"runtime.uint64tofloat32", obj.ABIInternal},
	{"runtime.uint32tofloat64", obj.ABIInternal},
	{"runtime.complex128div", obj.ABIInternal},
	{"runtime.racefuncenter", obj.ABIInternal},
	{"runtime.racefuncexit", obj.ABIInternal},
	{"runtime.raceread", obj.ABIInternal},
	{"runtime.racewrite", obj.ABIInternal},
	{"runtime.racereadrange", obj.ABIInternal},
	{"runtime.racewriterange", obj.ABIInternal},
	{"runtime.msanread", obj.ABIInternal},
	{"runtime.msanwrite", obj.ABIInternal},
	{"runtime.msanmove", obj.ABIInternal},
	{"runtime.asanread", obj.ABIInternal},
	{"runtime.asanwrite", obj.ABIInternal},
	{"runtime.checkptrAlignment", obj.ABIInternal},
	{"runtime.checkptrArithmetic", obj.ABIInternal},
	{"runtime.libfuzzerTraceCmp1", obj.ABIInternal},
	{"runtime.libfuzzerTraceCmp2", obj.ABIInternal},
	{"runtime.libfuzzerTraceCmp4", obj.ABIInternal},
	{"runtime.libfuzzerTraceCmp8", obj.ABIInternal},
	{"runtime.libfuzzerTraceConstCmp1", obj.ABIInternal},
	{"runtime.libfuzzerTraceConstCmp2", obj.ABIInternal},
	{"runtime.libfuzzerTraceConstCmp4", obj.ABIInternal},
	{"runtime.libfuzzerTraceConstCmp8", obj.ABIInternal},
	{"runtime.libfuzzerHookStrCmp", obj.ABIInternal},
	{"runtime.libfuzzerHookEqualFold", obj.ABIInternal},
	{"runtime.addCovMeta", obj.ABIInternal},
	{"runtime.x86HasAVX", obj.ABI0},
	{"runtime.x86HasFMA", obj.ABI0},
	{"runtime.x86HasPOPCNT", obj.ABI0},
	{"runtime.x86HasSSE41", obj.ABI0},
	{"runtime.armHasVFPv4", obj.ABI0},
	{"runtime.arm64HasATOMICS", obj.ABI0},
	{"runtime.loong64HasLAMCAS", obj.ABI0},
	{"runtime.loong64HasLAM_BH", obj.ABI0},
	{"runtime.loong64HasDBAR_HINTS", obj.ABI0},
	{"runtime.loong64HasLSX", obj.ABI0},
	{"runtime.riscv64HasZbb", obj.ABI0},
	{"runtime.asanregisterglobals", obj.ABIInternal},
	{"runtime.KeepAlive", obj.ABIInternal},
	{"runtime.deferproc", obj.ABIInternal},
	{"runtime.deferprocStack", obj.ABIInternal},
	{"runtime.deferreturn", obj.ABIInternal},
	{"runtime.newproc", obj.ABIInternal},
	{"runtime.panicoverflow", obj.ABIInternal},
	{"runtime.sigpanic", obj.ABIInternal},
	{"runtime.gcWriteBarrier1", obj.ABIInternal},
	{"runtime.gcWriteBarrier2", obj.ABIInternal},
	{"runtime.gcWriteBarrier3", obj.ABIInternal},
	{"runtime.gcWriteBarrier4", obj.ABIInternal},
	{"runtime.gcWriteBarrier5", obj.ABIInternal},
	{"runtime.gcWriteBarrier6", obj.ABIInternal},
	{"runtime.gcWriteBarrier7", obj.ABIInternal},
	{"runtime.gcWriteBarrier8", obj.ABIInternal},
	{"runtime.duffzero", obj.ABIInternal},
	{"runtime.duffcopy", obj.ABIInternal},
	{"runtime.morestack", obj.ABI0},
	{"runtime.morestackc", obj.ABI0},
	{"runtime.morestack_noctxt", obj.ABI0},
	{"runtime.retpolineAX", obj.ABI0},
	{"runtime.retpolineCX", obj.ABI0},
	{"runtime.retpolineDX", obj.ABI0},
	{"runtime.retpolineBX", obj.ABI0},
	{"runtime.retpolineBP", obj.ABI0},
	{"runtime.retpolineSI", obj.ABI0},
	{"runtime.retpolineDI", obj.ABI0},
	{"runtime.retpolineR8", obj.ABI0},
	{"runtime.retpolineR9", obj.ABI0},
	{"runtime.retpolineR10", obj.ABI0},
	{"runtime.retpolineR11", obj.ABI0},
	{"runtime.retpolineR12", obj.ABI0},
	{"runtime.retpolineR13", obj.ABI0},
	{"runtime.retpolineR14", obj.ABI0},
	{"runtime.retpolineR15", obj.ABI0},
	{"runtime.tls_g", obj.ABI0},
	{"type:int8", obj.ABI0},
	{"type:*int8", obj.ABI0},
	{"type:uint8", obj.ABI0},
	{"type:*uint8", obj.ABI0},
	{"type:int16", obj.ABI0},
	{"type:*int16", obj.ABI0},
	{"type:uint16", obj.ABI0},
	{"type:*uint16", obj.ABI0},
	{"type:int32", obj.ABI0},
	{"type:*int32", obj.ABI0},
	{"type:uint32", obj.ABI0},
	{"type:*uint32", obj.ABI0},
	{"type:int64", obj.ABI0},
	{"type:*int64", obj.ABI0},
	{"type:uint64", obj.ABI0},
	{"type:*uint64", obj.ABI0},
	{"type:float32", obj.ABI0},
	{"type:*float32", obj.ABI0},
	{"type:float64", obj.ABI0},
	{"type:*float64", obj.ABI0},
	{"type:complex64", obj.ABI0},
	{"type:*complex64", obj.ABI0},
	{"type:complex128", obj.ABI0},
	{"type:*complex128", obj.ABI0},
	{"type:unsafe.Pointer", obj.ABI0},
	{"type:*unsafe.Pointer", obj.ABI0},
	{"type:uintptr", obj.ABI0},
	{"type:*uintptr", obj.ABI0},
	{"type:bool", obj.ABI0},
	{"type:*bool", obj.ABI0},
	{"type:string", obj.ABI0},
	{"type:*string", obj.ABI0},
	{"type:error", obj.ABI0},
	{"type:*error", obj.ABI0},
	{"type:func(error) string", obj.ABI0},
	{"type:*func(error) string", obj.ABI0},
}

// BuiltinName returns the name and ABI of builtin i, and whether i names
// one at all.
func BuiltinName(i int) (name string, abi uint16, ok bool) {
	if i < 0 || i >= len(builtins) {
		return "", 0, false
	}
	return builtins[i].name, builtins[i].abi, true
}

// NumBuiltin is how many predeclared symbols the format defines.
func NumBuiltin() int { return len(builtins) }

// builtinByName is the reverse of the list. The ABI is part of the key
// because two entries share a name and differ only in it.
var builtinByName = func() map[builtinKey]int {
	m := make(map[builtinKey]int, len(builtins))
	for i, b := range builtins {
		m[builtinKey{b.name, b.abi}] = i
	}
	return m
}()

type builtinKey struct {
	name string
	abi  uint16
}

// builtinIndex returns the position of a predeclared symbol in the list,
// or -1.
func builtinIndex(name string, abi uint16) int {
	if i, ok := builtinByName[builtinKey{name, abi}]; ok {
		return i
	}
	return -1
}
