// Code generated by types2/gen. DO NOT EDIT.
// Source: ../upstream/types2/util_test.go.txt

// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file exports various functionality of util.go
// so that it can be used in (package-external) tests.

package types2

import (
	"golang.design/x/nanogo/syntax"
)

func CmpPos(p, q syntax.Pos) int { return cmpPos(p, q) }

func ScopeComment(s *Scope) string         { return s.comment }
func ObjectScopePos(obj Object) syntax.Pos { return obj.scopePos() }
