// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package ssagen

import (
	"fmt"
	"strings"

	"golang.design/x/nanogo/ir"
	"golang.design/x/nanogo/syntax"
)

// The compiler-generated method wrappers.
//
// A descriptor's Method holds two code pointers, and
// specs/032-type-descriptors-and-itabs.md gives them their names:
//
//   - Tfn takes the receiver the method was declared with.
//   - Ifn takes a one-word receiver, which is what an itab call passes.
//
// For a value receiver on a type that is not stored directly in an interface,
// those are two different functions: Tfn is the method itself and Ifn takes a
// pointer, loads the receiver through it and calls the method. The second one
// is not declared anywhere, so the compiler generates it. gc generates the
// same function in the same place (cmd/compile/internal/noder, methodWrapper
// with one deref).
//
// One generated function covers every use. A defined type T with a value
// receiver method M produces exactly one wrapper, (*T).M, and the four fields
// that can name a function name either the method or that wrapper:
//
//	descriptor  method receiver  Tfn         Ifn
//	T           value            T.M         T.M if T is one pointer word,
//	                                         else (*T).M
//	*T          value            (*T).M      (*T).M
//	*T          pointer          (*T).M      (*T).M
//
// A pointer receiver method is already spelled (*T).M by the front end, so the
// bottom row needs nothing generated. The middle row is why the wrapper is
// emitted for a type that is one pointer word as well: *T's descriptor names
// it whatever T's shape is.
//
// # Why this is a call and not a tail call
//
// gc emits an OTAILCALL, so the wrapper leaves no frame behind. nanogo has no
// tail call, so the wrapper calls and returns. The difference is one frame,
// and the frame is why [ir.Func.Wrapper] is set on every function built here:
// runtime.gorecover counts the frames between itself and runtime.gopanic and
// skips every frame whose funcID is FuncIDWrapper, so a wrapper that did not
// carry the mark would stop a recover from recovering.

// wrapperPos is the position every generated function carries.
//
// It is the zero position, which resolves to no file and no line. gc uses
// base.AutogeneratedPos for the same reason: the code is not in any source
// file, so a position that named one would send a debugger and a traceback to
// a line that has nothing to do with the frame.
var wrapperPos syntax.Pos

// wrapperFile is the file name the pc-file table carries for generated code.
//
// It is gc's spelling. [Emit] substitutes it for an empty Options.File
// already; naming it here keeps the driver from having to know that.
const wrapperFile = "<autogenerated>"

// MethodWrappers returns the generated functions the descriptors of types owe,
// in a deterministic order.
//
// The input is the set of types whose descriptors a package emits, which is
// what makes the result the set that package owes: a descriptor names a
// wrapper, so whoever writes the descriptor writes the wrapper. gc decides the
// same set at the same point, from reflectdata's method list.
//
// Every wrapper is emitted whether the descriptor that would name it is the
// one for T or the one for *T, because the two descriptors are written from
// one method set and either may be the one this package holds. The symbols are
// duplicate-tolerant, so a second package that emits the same wrapper is one
// symbol after the link and not a duplicate definition.
func MethodWrappers(types []*ir.Type) ([]*ir.Func, error) {
	var out []*ir.Func
	// seen is a lookup table and is never ranged over
	// (specs/053-determinism.md). The key is the symbol, because T and *T
	// reach the same wrapper and two converters produce two ir.Types for one
	// Go type.
	seen := make(map[string]bool)
	for _, t := range types {
		base := t
		if base != nil && base.Kind == ir.Ptr {
			base = base.Elem
		}
		if base == nil || base.Name == "" || base.Kind == ir.Interface {
			// A method is declared on a defined type and on nothing else, and
			// an interface's methods are its own rather than declared on it.
			continue
		}
		for _, m := range base.Methods {
			if m.PtrOnly {
				// The declaration already has a pointer receiver, so the
				// method itself is the function both fields name.
				continue
			}
			fn, err := methodWrapper(base, m)
			if err != nil {
				return nil, err
			}
			if seen[fn.Sym] {
				continue
			}
			seen[fn.Sym] = true
			out = append(out, fn)
		}
	}
	return out, nil
}

// methodWrapper builds (*T).M for a value receiver method M of T.
//
// The body is one statement:
//
//	func (p *T) M(a ...) (r ...) { return T.M(*p, a...) }
//
// The deref is what makes it a wrapper: the caller holds a pointer, the method
// wants the value, and the load is the whole of the adaptation. There is no
// nil check. gc emits a call to runtime.panicwrap here so that the panic names
// the method, and the deref of a nil pointer faults into the same panic
// without it. specs/031-runtime-lowering.md is the only place a runtime symbol
// may be spelled and panicwrap is not in it, so the message is the fault's
// rather than the wrapper's, and the behaviour is the same.
func methodWrapper(t *ir.Type, m ir.Method) (*ir.Func, error) {
	sym, err := ir.MethodSymbol(t, m, true)
	if err != nil {
		return nil, err
	}
	if m.Sig == nil {
		return nil, fmt.Errorf("ssagen: the wrapper %s needs the signature of %s, which the IR does not carry", sym, m.Name)
	}
	if m.Sig.Variadic {
		// The wrapper passes its parameters through unchanged, so the packed
		// slice arrives already packed and the call must not pack it again.
		// ir.Build spells that with an OCall index it does not export, so a
		// variadic method is refused rather than silently repacked.
		return nil, fmt.Errorf("ssagen: the wrapper %s is for a variadic method, and passing a packed slice through is not built", sym)
	}
	ptr := &ir.Type{Kind: ir.Ptr, Elem: t}
	if err := ir.Layout(ptr); err != nil {
		return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
	}
	recv := &ir.Object{Name: ".this", Type: ptr, Class: ir.ClassParam, Pos: wrapperPos}
	fn := &ir.Func{
		Name:    "(*" + strings.TrimPrefix(t.Name, t.PkgPath+".") + ")." + m.Name,
		Sym:     sym,
		Pos:     wrapperPos,
		Recv:    recv,
		Wrapper: true,
	}
	// The call's arguments are the wrapper's own parameters, with the loaded
	// receiver in front. That is the shape ir.Build gives a call to a method
	// of a concrete type: the receiver is the first argument and the callee is
	// the method's symbol.
	args := []ir.Expr{{
		Op:   ir.ODeref,
		Pos:  wrapperPos,
		Type: t,
		X:    &ir.Node{Op: ir.OLocal, Pos: wrapperPos, Type: ptr, Obj: recv},
	}}
	for i, pt := range m.Sig.Params {
		o := &ir.Object{Name: fmt.Sprintf(".p%d", i), Type: pt, Class: ir.ClassParam, Pos: wrapperPos}
		fn.Params = append(fn.Params, o)
		args = append(args, &ir.Node{Op: ir.OLocal, Pos: wrapperPos, Type: pt, Obj: o})
	}
	for i, rt := range m.Sig.Results {
		fn.Results = append(fn.Results, &ir.Object{
			Name: fmt.Sprintf(".r%d", i), Type: rt, Class: ir.ClassResult, Pos: wrapperPos,
		})
	}
	target, err := ir.MethodSymbol(t, m, false)
	if err != nil {
		return nil, err
	}
	res, err := callResultType(m.Sig.Results)
	if err != nil {
		return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
	}
	call := &ir.Node{
		Op:   ir.OCall,
		Pos:  wrapperPos,
		Type: res,
		X: &ir.Node{Op: ir.OGlobal, Pos: wrapperPos, Type: m.Sig, Obj: &ir.Object{
			Name: target, Type: m.Sig, Class: ir.ClassFunc, Pos: wrapperPos,
		}},
		Args: args,
	}
	ret := &ir.Node{Op: ir.OReturn, Pos: wrapperPos, Type: res}
	if len(m.Sig.Results) > 0 {
		// return T.M(*p, a...). One argument whose type covers every result,
		// which is the form ir.Build gives "return f()" when f returns
		// everything the function returns.
		ret.Type = voidType()
		ret.Args = []ir.Expr{call}
		fn.Body = []ir.Stmt{ret}
		return fn, nil
	}
	fn.Body = []ir.Stmt{call, ret}
	return fn, nil
}

// callResultType is the type of the value a call to a function with these
// results produces.
//
// It is ir.Build's resultType: void for none, the type itself for one, and a
// tuple for more. The tuple's field names are ir.Converter's, because
// specs/021-ssa-construction.md reads a call's components out of the fields.
func callResultType(results []*ir.Type) (*ir.Type, error) {
	switch len(results) {
	case 0:
		return voidType(), nil
	case 1:
		return results[0], nil
	}
	t := &ir.Type{Kind: ir.Tuple}
	for i, r := range results {
		t.Fields = append(t.Fields, ir.Field{Name: fmt.Sprintf("r%d", i), Type: r})
	}
	if err := ir.Layout(t); err != nil {
		return nil, err
	}
	return t, nil
}

// voidType is the type of an expression with no value.
//
// It is built once and shared, as ir.Build's is: nothing below the IR reads a
// field of it, so one instance for the whole compiler is correct and a fresh
// one per statement is only garbage.
var voidType = func() func() *ir.Type {
	t := &ir.Type{Kind: ir.Void}
	if err := ir.Layout(t); err != nil {
		panic("ssagen: void does not lay out: " + err.Error())
	}
	return func() *ir.Type { return t }
}()
