// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package ssagen

import (
	"fmt"
	"strings"

	"golang.design/x/nanogo/ir"
	"golang.design/x/nanogo/syntax"
)

// The compiler-generated method wrappers.
//
// A descriptor's Method holds two code pointers, and
// specs/032-type-descriptors-and-itabs.md gives them their names:
//
//   - Tfn takes the receiver the method was declared with.
//   - Ifn takes a one-word receiver, which is what an itab call passes.
//
// For a value receiver on a type that is not stored directly in an interface,
// those are two different functions: Tfn is the method itself and Ifn takes a
// pointer, loads the receiver through it and calls the method. The second one
// is not declared anywhere, so the compiler generates it. gc generates the
// same function in the same place (cmd/compile/internal/noder, methodWrapper
// with one deref).
//
// One generated function covers every use. A defined type T with a value
// receiver method M produces exactly one wrapper, (*T).M, and the four fields
// that can name a function name either the method or that wrapper:
//
//	descriptor  method receiver  Tfn         Ifn
//	T           value            T.M         T.M if T is one pointer word,
//	                                         else (*T).M
//	*T          value            (*T).M      (*T).M
//	*T          pointer          (*T).M      (*T).M
//
// A pointer receiver method is already spelled (*T).M by the front end, so the
// bottom row needs nothing generated. The middle row is why the wrapper is
// emitted for a type that is one pointer word as well: *T's descriptor names
// it whatever T's shape is.
//
// # Why this is a call and not a tail call
//
// gc emits an OTAILCALL, so the wrapper leaves no frame behind. nanogo has no
// tail call, so the wrapper calls and returns. The difference is one frame,
// and the frame is why [ir.Func.Wrapper] is set on every function built here:
// runtime.gorecover counts the frames between itself and runtime.gopanic and
// skips every frame whose funcID is FuncIDWrapper, so a wrapper that did not
// carry the mark would stop a recover from recovering.

// wrapperPos is the position every generated function carries.
//
// It is the zero position, which resolves to no file and no line. gc uses
// base.AutogeneratedPos for the same reason: the code is not in any source
// file, so a position that named one would send a debugger and a traceback to
// a line that has nothing to do with the frame.
var wrapperPos syntax.Pos

// wrapperFile is the file name the pc-file table carries for generated code.
//
// It is gc's spelling. [Emit] substitutes it for an empty Options.File
// already; naming it here keeps the driver from having to know that.
const wrapperFile = "<autogenerated>"

// MethodWrappers returns the generated functions the descriptors of types owe,
// in a deterministic order.
//
// The input is the set of types whose descriptors a package emits, which is
// what makes the result the set that package owes: a descriptor names a
// wrapper, so whoever writes the descriptor writes the wrapper. gc decides the
// same set at the same point, from reflectdata's method list.
//
// Every wrapper is emitted whether the descriptor that would name it is the
// one for T or the one for *T, because the two descriptors are written from
// one method set and either may be the one this package holds. The symbols are
// duplicate-tolerant, so a second package that emits the same wrapper is one
// symbol after the link and not a duplicate definition.
//
// pkg is the import path of the package being compiled and declared holds the
// symbol of every function it declares. The two answer one question that
// [ir.Method] cannot: whether the method is declared on the type or promoted
// into it from an embedded field. ir.Type.Methods is the whole method set, so
// a promoted entry and a declared one look alike, and the two owe opposite
// things. A declared value receiver method owes the pointer wrapper below and
// nothing else, and a promoted one owes a wrapper for each receiver form the
// method set puts it in, because no declaration spells either.
func MethodWrappers(types []*ir.Type, pkg string, declared map[string]bool) ([]*ir.Func, error) {
	var out []*ir.Func
	// seen is a lookup table and is never ranged over
	// (specs/053-determinism.md). The key is the symbol, because T and *T
	// reach the same wrapper and two converters produce two ir.Types for one
	// Go type.
	seen := make(map[string]bool)
	add := func(fn *ir.Func) {
		if seen[fn.Sym] {
			return
		}
		seen[fn.Sym] = true
		out = append(out, fn)
	}
	for _, t := range types {
		base := t
		if base != nil && base.Kind == ir.Ptr {
			base = base.Elem
		}
		if base == nil || base.Name == "" || base.Kind == ir.Interface {
			// A method is declared on a defined type and on nothing else, and
			// an interface's methods are its own rather than declared on it.
			continue
		}
		for _, m := range base.Methods {
			p, err := promotionOf(base, m, pkg, declared)
			if err != nil {
				return nil, err
			}
			if p == nil {
				if m.PtrOnly {
					// The declaration already has a pointer receiver, so the
					// method itself is the function both fields name.
					continue
				}
				fn, err := methodWrapper(base, m)
				if err != nil {
					return nil, err
				}
				add(fn)
				continue
			}
			// A promoted method is declared on the embedded type, so neither
			// receiver form of this type names a function the front end
			// compiled. *T's method set holds every promoted method and T's
			// holds the ones the language promotes into a value, which is the
			// same rule Method.PtrOnly records.
			if !m.PtrOnly {
				fn, err := promotedWrapper(base, m, p, false)
				if err != nil {
					return nil, err
				}
				add(fn)
			}
			fn, err := promotedWrapper(base, m, p, true)
			if err != nil {
				return nil, err
			}
			add(fn)
		}
	}
	return out, nil
}

// methodWrapper builds (*T).M for a value receiver method M of T.
//
// The body is one statement:
//
//	func (p *T) M(a ...) (r ...) { return T.M(*p, a...) }
//
// The deref is what makes it a wrapper: the caller holds a pointer, the method
// wants the value, and the load is the whole of the adaptation. There is no
// nil check. gc emits a call to runtime.panicwrap here so that the panic names
// the method, and the deref of a nil pointer faults into the same panic
// without it. specs/031-runtime-lowering.md is the only place a runtime symbol
// may be spelled and panicwrap is not in it, so the message is the fault's
// rather than the wrapper's, and the behaviour is the same.
func methodWrapper(t *ir.Type, m ir.Method) (*ir.Func, error) {
	sym, err := ir.MethodSymbol(t, m, true)
	if err != nil {
		return nil, err
	}
	if err := wrappable(sym, m); err != nil {
		return nil, err
	}
	ptr, err := pointerTo(t)
	if err != nil {
		return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
	}
	recv := &ir.Object{Name: ".this", Type: ptr, Class: ir.ClassParam, Pos: wrapperPos}
	fn := &ir.Func{
		Name:    "(*" + shortName(t) + ")." + m.Name,
		Sym:     sym,
		Pos:     wrapperPos,
		Recv:    recv,
		Wrapper: true,
	}
	target, err := ir.MethodSymbol(t, m, false)
	if err != nil {
		return nil, err
	}
	arg := &ir.Node{
		Op:   ir.ODeref,
		Pos:  wrapperPos,
		Type: t,
		X:    &ir.Node{Op: ir.OLocal, Pos: wrapperPos, Type: ptr, Obj: recv},
	}
	return finishWrapper(fn, sym, m.Sig, arg, wrapperCallee(target, m.Sig))
}

// wrappable reports the reason a method cannot be forwarded through a
// generated function at all.
func wrappable(sym string, m ir.Method) error {
	if m.Sig == nil {
		return fmt.Errorf("ssagen: the wrapper %s needs the signature of %s, which the IR does not carry", sym, m.Name)
	}
	// A variadic method needs nothing special here, and the refusal that used
	// to sit at this line was written from a wrong reading.
	//
	// The worry was that the wrapper would pack its last parameter into a
	// second slice. It cannot. Packing happens once, in ir.Build's callArgs,
	// which reads the ... from the syntax of a call; [ir.Type.Params] is what
	// comes out of it, and for func(...int) the last entry is already []int.
	// A wrapper built from that list forwards a slice to a parameter that is a
	// slice, which is the same pass-through every other parameter gets, and
	// nothing below OCall reads [ir.Type.Variadic] except the descriptor
	// writer.
	return nil
}

// shortName is the identifier a defined type's name carries once its import
// path is taken off, which is what [ir.Func.Name] spells the receiver with.
func shortName(t *ir.Type) string {
	return strings.TrimPrefix(t.Name, t.PkgPath+".")
}

// finishWrapper gives fn the parameters and results of sig and a body that
// forwards them to target with recv in front.
//
// The call's arguments are the wrapper's own parameters, with the adapted
// receiver in front. That is the shape ir.Build gives a call to a method of a
// concrete type: the receiver is the first argument and the callee is the
// method's symbol.
func finishWrapper(fn *ir.Func, sym string, sig *ir.Type, recv ir.Expr, callee *ir.Object) (*ir.Func, error) {
	var args []ir.Expr
	if recv != nil {
		// A method wrapper puts the adapted receiver in front. An ABI wrapper
		// has no receiver at all, and a nil expression here is what says so:
		// an empty leading argument would be placed at offset 0 of the
		// callee's area, which is where the convention puts a receiver.
		args = append(args, recv)
	}
	for i, pt := range sig.Params {
		o := &ir.Object{Name: fmt.Sprintf(".p%d", i), Type: pt, Class: ir.ClassParam, Pos: wrapperPos}
		fn.Params = append(fn.Params, o)
		args = append(args, &ir.Node{Op: ir.OLocal, Pos: wrapperPos, Type: pt, Obj: o})
	}
	for i, rt := range sig.Results {
		fn.Results = append(fn.Results, &ir.Object{
			Name: fmt.Sprintf(".r%d", i), Type: rt, Class: ir.ClassResult, Pos: wrapperPos,
		})
	}
	res, err := callResultType(sig.Results)
	if err != nil {
		return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
	}
	call := &ir.Node{
		Op:   ir.OCall,
		Pos:  wrapperPos,
		Type: res,
		X:    &ir.Node{Op: ir.OGlobal, Pos: wrapperPos, Type: sig, Obj: callee},
		Args: args,
	}
	ret := &ir.Node{Op: ir.OReturn, Pos: wrapperPos, Type: res}
	if len(sig.Results) > 0 {
		// return T.M(*p, a...). One argument whose type covers every result,
		// which is the form ir.Build gives "return f()" when f returns
		// everything the function returns.
		ret.Type = voidType()
		ret.Args = []ir.Expr{call}
		fn.Body = []ir.Stmt{ret}
		return fn, nil
	}
	fn.Body = []ir.Stmt{call, ret}
	return fn, nil
}

// The promoted method wrappers.
//
// A struct type promotes the methods of an embedded field, so a defined type
// that declares nothing can still have a method set.
// specs/032-type-descriptors-and-itabs.md names the itab's Fun entries and the
// descriptor's Method array T.M and (*T).M, and a promoted M is declared on
// the embedded type, so neither name belongs to a function the front end
// compiled. Without one generated here the descriptor and the itab relocate to
// a symbol nothing defines and the link fails.
//
// gc generates the same function, in noder.methodWrapper, and its body is
// typecheck.XDotMethod on the receiver: the selector expansion inserts the
// embedded fields the source leaves implicit and an OTAILCALL enters the
// declaration. The walk below writes that path out, because nanogo has no tail
// call and because ir.Method carries no path of its own.

// promotion is the route from a defined type to the declaration of one of its
// methods.
type promotion struct {
	// path holds the index of the embedded field to select at each step,
	// outermost first. It is never empty: a method the type declares is not a
	// promotion.
	path []int

	// meth is the entry the type the last step reaches holds for the method.
	// It is read for PtrOnly, which says which receiver form the declaration
	// has and so which of the two symbols the call names.
	meth ir.Method
}

// maxPromotionDepth bounds the walk from a type to the declaration.
//
// ir.Converter's collectMethodNames bounds its own walk with the same number
// and for the same reason: embedding cannot nest for ever in a well-formed
// program, and a graph that is merely enormous is what the bound is for.
const maxPromotionDepth = 64

// promotionOf returns the route from t to the declaration of m, or nil when m
// is declared on t and there is no route.
func promotionOf(t *ir.Type, m ir.Method, pkg string, declared map[string]bool) (*promotion, error) {
	fail := func(err error) (*promotion, error) {
		return nil, fmt.Errorf("ssagen: the wrapper for the method %s of %s: %w", m.Name, t, err)
	}
	if stopsAt(t, m, pkg, declared) {
		return nil, nil
	}
	var path []int
	cur := t
	for len(path) < maxPromotionDepth {
		i, next, err := bestSource(cur, m, pkg, declared, maxPromotionDepth)
		if err != nil {
			return fail(err)
		}
		path = append(path, i)
		cur = next
		if !stopsAt(cur, m, pkg, declared) {
			continue
		}
		if cur.Kind == ir.Interface {
			// An interface's method is declared by nobody, so there is no
			// symbol for the call to name and a generated wrapper would
			// relocate against a name nothing defines. ir.Build refuses the
			// sibling case, a method expression on an interface, in these
			// words.
			return fail(fmt.Errorf("it is promoted from the embedded interface %s, whose method is declared by nobody, "+
				"and the wrapper that calls the method through the itab is not generated", cur))
		}
		own, ok := methodEntry(cur, m)
		if !ok {
			return fail(fmt.Errorf("the walk reached %s, whose method set does not hold it", cur))
		}
		return &promotion{path: path, meth: own}, nil
	}
	return fail(fmt.Errorf("the declaration is more than %d embedded fields away", maxPromotionDepth))
}

// stopsAt reports whether the walk from a promoted method ends at t, so that
// nothing below t is forwarded past.
//
// The answers, in this order. An unnamed struct declares nothing, because a
// method is declared on a defined type and on nothing else, so a walk that
// reached one through an alias to it keeps going. An interface ends the walk
// with nowhere to go, which promotionOf refuses by name. A type declared in
// another package is stopped at because that package defined every entry point
// its method set names, which is gc's rule: noder.needWrapper puts an imported
// type in haveWrapperTypes and generates nothing for it, and
// specs/040-object-format.md makes a generated wrapper duplicate-tolerant, so
// the declaring package's own definition is the one cmd/link keeps. A symbol
// this package declares is the declaration itself, which is what a method that
// shadows a promoted one of the same name produces. What is left is a type
// whose method set holds m and none of whose embedded fields do, and in a
// package this compiler is compiling that can only be a declaration.
func stopsAt(t *ir.Type, m ir.Method, pkg string, declared map[string]bool) bool {
	if t == nil {
		return true
	}
	if t.Kind == ir.Interface {
		return true
	}
	if t.Name == "" {
		return false
	}
	if t.PkgPath != pkg {
		return true
	}
	for _, ptr := range [2]bool{false, true} {
		sym, err := ir.MethodSymbol(t, m, ptr)
		if err == nil && declared[sym] {
			return true
		}
	}
	return len(embeddedSources(t, m)) == 0
}

// embeddedSources returns the index of every embedded field of t whose type
// carries m.
func embeddedSources(t *ir.Type, m ir.Method) []int {
	var idx []int
	for i := range t.Fields {
		if f := &t.Fields[i]; f.Embedded && carriesMethod(embeddedBase(f.Type), m, maxPromotionDepth) {
			idx = append(idx, i)
		}
	}
	return idx
}

// embeddedBase is the type an embedded field promotes the methods of, which is
// the element of an embedded pointer field and the field's own type otherwise.
func embeddedBase(t *ir.Type) *ir.Type {
	if t != nil && t.Kind == ir.Ptr {
		return t.Elem
	}
	return t
}

// carriesMethod reports whether t's method set holds m.
//
// A defined type and an interface carry their own method set. An unnamed
// struct carries no method of its own and is not opaque either: an alias to
// one can be embedded, and the methods of what that struct embeds are promoted
// through it, so the question passes down to its embedded fields.
func carriesMethod(t *ir.Type, m ir.Method, budget int) bool {
	if t == nil || budget <= 0 {
		return false
	}
	if t.Name != "" || t.Kind == ir.Interface {
		_, ok := methodEntry(t, m)
		return ok
	}
	if t.Kind != ir.Struct {
		return false
	}
	for i := range t.Fields {
		if f := &t.Fields[i]; f.Embedded && carriesMethod(embeddedBase(f.Type), m, budget-1) {
			return true
		}
	}
	return false
}

// bestSource returns the embedded field of t that m is promoted through.
//
// The language selects the shallowest declaration, where the depth of a method
// declared in an embedded field is one more than its depth in that field's
// type. ir.Type.Methods is a whole method set rather than a list of
// declarations, so every embedded field that carries m at any depth is a
// candidate here and the depth is what separates them. A tie is not selectable
// by the language either, so it is refused rather than resolved.
func bestSource(t *ir.Type, m ir.Method, pkg string, declared map[string]bool, budget int) (int, *ir.Type, error) {
	if budget <= 0 {
		return 0, nil, fmt.Errorf("the declaration is more than %d embedded fields away", maxPromotionDepth)
	}
	idx := embeddedSources(t, m)
	if len(idx) == 0 {
		return 0, nil, fmt.Errorf("the method set of %s holds it and no embedded field of %s carries it", t, t)
	}
	best, ties, depth := 0, 1, 0
	for k, i := range idx {
		d, err := declarationDepth(embeddedBase(t.Fields[i].Type), m, pkg, declared, budget-1)
		if err != nil {
			return 0, nil, err
		}
		switch {
		case k == 0 || d < depth:
			best, ties, depth = k, 1, d
		case d == depth:
			ties++
		}
	}
	if ties > 1 {
		return 0, nil, fmt.Errorf("two embedded fields of %s declare it the same distance away, and the one the language selects is not decided here", t)
	}
	return idx[best], embeddedBase(t.Fields[idx[best]].Type), nil
}

// declarationDepth is how many embedded fields separate t from the declaration
// of m, and is zero when the walk stops at t.
func declarationDepth(t *ir.Type, m ir.Method, pkg string, declared map[string]bool, budget int) (int, error) {
	if stopsAt(t, m, pkg, declared) {
		return 0, nil
	}
	_, next, err := bestSource(t, m, pkg, declared, budget)
	if err != nil {
		return 0, err
	}
	d, err := declarationDepth(next, m, pkg, declared, budget-1)
	if err != nil {
		return 0, err
	}
	return d + 1, nil
}

// methodEntry returns t's own entry for the method m names.
//
// Name, package path and signature together, because a promoted method keeps
// all three and a name alone is not the method: two unexported methods of one
// name from two packages are two methods, and a field or a method of the same
// name with another signature is a different one again. The signature is
// compared as the link string [ir.TypeSymbol] writes, which is the same
// identity cmd/link resolves the descriptor's Mtyp by. A signature that has no
// link string is not compared, so a gap in the IR narrows the test rather than
// failing it.
func methodEntry(t *ir.Type, m ir.Method) (ir.Method, bool) {
	if t == nil {
		return ir.Method{}, false
	}
	want := sigKey(m.Sig)
	for _, c := range t.Methods {
		if c.Name != m.Name || c.Pkg != m.Pkg {
			continue
		}
		if got := sigKey(c.Sig); want != "" && got != "" && got != want {
			continue
		}
		return c, true
	}
	return ir.Method{}, false
}

// sigKey is a signature's link string, or the empty string when it has none.
func sigKey(sig *ir.Type) string {
	if sig == nil {
		return ""
	}
	s, err := ir.TypeSymbol(sig)
	if err != nil {
		return ""
	}
	return s
}

// promotedWrapper builds T.M or (*T).M for a method M that T promotes.
//
// The body is one statement, the path the source leaves implicit written out:
//
//	func (p *T) M(a ...) (r ...) { return (*E).M(&(*p).e.f, a...) }
//
// A step through an embedded pointer field loads the pointer, and that load is
// where a nil embedded pointer faults. gc's wrapper faults in the same place,
// because typecheck.XDotMethod expands the same path and inserts the same
// dereference. There is no nil check of the receiver: the pointer form of this
// wrapper dereferences its own receiver at the first step, which faults the way
// the deref wrapper above does.
//
// The last step is adapted to the receiver the declaration takes. A pointer
// receiver on a value the walk reached needs its address, which is available
// exactly when the walk passed through a pointer: the address is then an offset
// from a pointer the wrapper loaded and not the address of a parameter. The
// language promotes a pointer receiver method into a value's method set only
// through an embedded pointer, so the case with no pointer to offset from
// cannot arise, and it is refused rather than assumed.
func promotedWrapper(t *ir.Type, m ir.Method, p *promotion, ptrRecv bool) (*ir.Func, error) {
	sym, err := ir.MethodSymbol(t, m, ptrRecv)
	if err != nil {
		return nil, err
	}
	if err := wrappable(sym, m); err != nil {
		return nil, err
	}
	recvType, name := t, shortName(t)+"."+m.Name
	if ptrRecv {
		if recvType, err = pointerTo(t); err != nil {
			return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
		}
		name = "(*" + shortName(t) + ")." + m.Name
	}
	recv := &ir.Object{Name: ".this", Type: recvType, Class: ir.ClassParam, Pos: wrapperPos}
	fn := &ir.Func{Name: name, Sym: sym, Pos: wrapperPos, Recv: recv, Wrapper: true}

	cur := &ir.Node{Op: ir.OLocal, Pos: wrapperPos, Type: recvType, Obj: recv}
	curType := recvType
	// Whether the place the walk names is one the wrapper can take the address
	// of. A dereference anywhere above it makes it so, because ir.markAddrtaken
	// walks from an address through the field selections to the storage it
	// names and stops at a dereference, which names no frame slot.
	addressable := false
	for _, i := range p.path {
		if curType.Kind == ir.Ptr {
			curType = curType.Elem
			cur = &ir.Node{Op: ir.ODeref, Pos: wrapperPos, Type: curType, X: cur}
			addressable = true
		}
		if curType.Kind != ir.Struct || i < 0 || i >= len(curType.Fields) {
			return nil, fmt.Errorf("ssagen: the wrapper %s selects field %d of %s, which does not have one", sym, i, curType)
		}
		curType = curType.Fields[i].Type
		cur = &ir.Node{Op: ir.OField, Pos: wrapperPos, Type: curType, X: cur, Index: i}
	}
	decl := curType
	switch {
	case p.meth.PtrOnly && curType.Kind != ir.Ptr:
		if !addressable {
			return nil, fmt.Errorf("ssagen: the wrapper %s needs the address of an embedded field of a receiver held by value", sym)
		}
		pt, err := pointerTo(curType)
		if err != nil {
			return nil, fmt.Errorf("ssagen: %s: %w", sym, err)
		}
		cur = &ir.Node{Op: ir.OAddr, Pos: wrapperPos, Type: pt, X: cur}
	case !p.meth.PtrOnly && curType.Kind == ir.Ptr:
		decl = curType.Elem
		cur = &ir.Node{Op: ir.ODeref, Pos: wrapperPos, Type: decl, X: cur}
	case curType.Kind == ir.Ptr:
		decl = curType.Elem
	}
	target, err := ir.MethodSymbol(decl, p.meth, p.meth.PtrOnly)
	if err != nil {
		return nil, err
	}
	return finishWrapper(fn, sym, m.Sig, cur, wrapperCallee(target, m.Sig))
}

// callResultType is the type of the value a call to a function with these
// results produces.
//
// It is ir.Build's resultType: void for none, the type itself for one, and a
// tuple for more. The tuple's field names are ir.Converter's, because
// specs/021-ssa-construction.md reads a call's components out of the fields.
func callResultType(results []*ir.Type) (*ir.Type, error) {
	switch len(results) {
	case 0:
		return voidType(), nil
	case 1:
		return results[0], nil
	}
	t := &ir.Type{Kind: ir.Tuple}
	for i, r := range results {
		t.Fields = append(t.Fields, ir.Field{Name: fmt.Sprintf("r%d", i), Type: r})
	}
	if err := ir.Layout(t); err != nil {
		return nil, err
	}
	return t, nil
}

// voidType is the type of an expression with no value.
//
// It is built once and shared, as ir.Build's is: nothing below the IR reads a
// field of it, so one instance for the whole compiler is correct and a fresh
// one per statement is only garbage.
var voidType = func() func() *ir.Type {
	t := &ir.Type{Kind: ir.Void}
	if err := ir.Layout(t); err != nil {
		panic("ssagen: void does not lay out: " + err.Error())
	}
	return func() *ir.Type { return t }
}()

// The ABI wrappers of specs/047-abi-wrappers.md.
//
// A bodyless Go declaration that an assembly file defines under ABI0 is two
// symbols and not one. The ABI is half of a symbol's identity in the object
// format, so internal/cpu.getisar0 under ABI0 and internal/cpu.getisar0 under
// ABIInternal are two names the linker keeps apart, and a Go call names the
// second. The wrapper is the second: it takes its arguments where a Go caller
// puts them, writes them where the assembly reads them, calls, and reads the
// results back.
//
// gc's makeABIWrapper builds the same function the same way, as an ir.Func
// with a body of one call and one return, and lets the ordinary pipeline
// compile it. That is not a convenience. A pointer argument of the wrapper is
// live across the inner call, so the collector has to find it, and it does
// because the wrapper went through the ordinary liveness pass
// (specs/027-liveness-and-stackmaps.md). A wrapper emitted by a shortcut path
// would have to answer that question again, by hand, for every shape.
//
// What gc does that nanogo does not: it emits a tail call for a signature
// with no parameters and no results, and it marks the wrapper NOSPLIT. nanogo
// has no tail call, and specs/035-goroutines-and-stack-growth.md forbids
// claiming NOSPLIT without computing the budget the claim rests on, so the
// wrapper carries the ordinary stack-growth prologue. The cost is one frame
// and one check; neither changes the answer.

// wrapperCallee is the object a generated wrapper's inner call names.
//
// The ABI travels with it. specs/030-abi.md makes the convention half of a
// symbol's identity, and [ir.Object.Assembly] is which half a reference names.
func wrapperCallee(target string, sig *ir.Type) *ir.Object {
	return &ir.Object{Name: target, Type: sig, Class: ir.ClassFunc, Pos: wrapperPos}
}

// ABIWrapper returns the ABIInternal wrapper a bodyless declaration owes.
//
// decl is the Go declaration and sym is the linker symbol the assembly
// defines, which is decl's own symbol unless a //go:linkname renamed it. The
// wrapper takes that name under ABIInternal and its inner call takes the same
// name under ABI0, which is why the two coexist: the relocation carries the
// convention, so the CALL in gc's own output prints the name of the TEXT it
// sits inside.
//
// A method is refused. gc refuses the same shape with "makeABIWrapper support
// for wrapping methods not implemented", and the receiver takes offset 0 of
// the ABI0 area, which nanogo's call walk recovers by a heuristic
// specs/030-abi.md already names as a bound.
func ABIWrapper(decl *ir.Func, sym string) (*ir.Func, error) {
	if decl == nil {
		return nil, fmt.Errorf("ssagen: an ABI wrapper for no declaration")
	}
	if decl.Type == nil {
		return nil, fmt.Errorf("ssagen: the ABI wrapper %s needs the signature of %s, which the IR does not carry", sym, decl.Name)
	}
	if decl.Recv != nil {
		return nil, fmt.Errorf("ssagen: the ABI wrapper %s is for a method, and the receiver takes offset 0 of the ABI0 area (specs/047-abi-wrappers.md)", sym)
	}
	if !decl.Bodyless {
		return nil, fmt.Errorf("ssagen: the ABI wrapper %s is for a declaration with a Go body, which would define the symbol twice", sym)
	}
	fn := &ir.Func{
		Name:    decl.Name,
		Sym:     sym,
		Pos:     wrapperPos,
		Wrapper: true,
	}
	callee := wrapperCallee(sym, decl.Type)
	callee.Assembly = true
	return finishWrapper(fn, sym, decl.Type, nil, callee)
}
