// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package driver

import (
	"bytes"
	"fmt"
	"go/constant"
	"os"

	"golang.design/x/nanogo/syntax"
	"golang.design/x/nanogo/types2"
)

// The assembly header, per specs/047-abi-wrappers.md.
//
// -asmhdr exists because an assembly file cannot compute a Go struct's field
// offsets. runtime/asm_arm64.s writes
//
//	MOVD (g_stack+stack_lo)(g), R2
//
// and g_stack and stack_lo are #defines the compiler produced from the Go
// declaration of type g struct. The header is the input to the second
// assembler run, so it has to be written even for a package that owes no
// wrapper: without it the assembler fails to find the #define.
//
// The rule is gc.dumpasmhdr in cmd/compile/internal/gc/export.go and nothing
// more. It walks typecheck.Target.AsmHdrDecls, which noder fills with every
// package-scope name whose Op is OLITERAL or OTYPE, collected only when
// -asmhdr is set, in the order the declarations were read. Nothing is
// filtered by whether the assembly refers to it.
//
// Exactness is the whole requirement. A writer that spells a constant
// differently from gc produces an assembly file that assembles to different
// code, and nothing reports it. asmhdr_test.go compares nanogo's output byte
// for byte against gc's for the eight packages the bootstrap closure refuses,
// runtime's 2622 lines included, because that is the only package with enough
// declarations to expose an ordering divergence.

// asmHdrHeader is the first line gc writes. The package is named by its name
// and not by its path, so internal/cpu prints "package cpu".
const asmHdrHeader = "// generated by compile -asmhdr from package %s\n\n"

// AsmHdr returns the -asmhdr header for a type-checked package.
//
// files are the package's source files in command-line order and info is the
// checker's record for them. The order is the declaration order of the source
// and it is not incidental: gc emits one #define per declaration as it reads
// them, and an assembly file that includes the header takes the last
// definition of a repeated name.
func AsmHdr(pkg *types2.Package, files []*syntax.File, info *types2.Info, sizes types2.Sizes) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, asmHdrHeader, pkg.Name())
	for _, f := range files {
		for _, d := range f.DeclList {
			switch d := d.(type) {
			case *syntax.ConstDecl:
				for _, n := range d.NameList {
					asmHdrConst(&b, info.Defs[n])
				}
			case *syntax.TypeDecl:
				asmHdrType(&b, info.Defs[d.Name], sizes)
			}
		}
	}
	return b.Bytes()
}

// asmHdrConst writes one constant, if gc would write it.
//
// A float or complex constant is skipped, because there is no spelling of one
// an assembler would take. Every other kind is written with
// constant.Value.ExactString, which is gc's own call: an integer prints in
// decimal, a boolean prints true or false, and a string prints Go-quoted, so
// internal/runtime/sys emits
//
//	#define const_ntz8tab "\b\x00\x01\x00..."
//
// for a 256-byte table. Nothing here reformats a value. A writer that spelled
// one differently would hand the assembler a different number.
func asmHdrConst(b *bytes.Buffer, obj types2.Object) {
	c, ok := obj.(*types2.Const)
	if !ok || c.Name() == "_" {
		return
	}
	switch c.Val().Kind() {
	case constant.Float, constant.Complex:
		return
	}
	fmt.Fprintf(b, "#define const_%s %v\n", c.Name(), c.Val().ExactString())
}

// asmHdrType writes one struct type's size and field offsets, if gc would
// write them.
//
// Only a struct is written. gc's test is t.IsStruct() over the declaration's
// type, which is the underlying type for an alias and for a defined type
// alike, so "type T = S" writes S's layout under the name T.
//
// A generic type is skipped. gc reaches it with an uninstantiated type whose
// size is not computed, and specs/047-abi-wrappers.md's rule holds: a value
// nanogo cannot spell exactly as gc does is refused rather than approximated.
// None of the eight packages the closure refuses declares one, which
// asmhdr_test.go's byte comparison is what confirms.
func asmHdrType(b *bytes.Buffer, obj types2.Object, sizes types2.Sizes) {
	tn, ok := obj.(*types2.TypeName)
	if !ok || tn.Name() == "_" {
		return
	}
	t := tn.Type()
	if named, ok := t.(*types2.Named); ok && named.TypeParams().Len() > 0 {
		return
	}
	st, ok := t.Underlying().(*types2.Struct)
	if !ok {
		return
	}
	fmt.Fprintf(b, "#define %s__size %d\n", tn.Name(), sizes.Sizeof(t))
	fields := make([]*types2.Var, st.NumFields())
	for i := range fields {
		fields[i] = st.Field(i)
	}
	offsets := sizes.Offsetsof(fields)
	for i, f := range fields {
		if f.Name() == "_" {
			continue
		}
		fmt.Fprintf(b, "#define %s_%s %d\n", tn.Name(), f.Name(), offsets[i])
	}
}

// writeAsmHdr writes the header to the file -asmhdr names.
//
// It is written on a compile that reaches code generation and not on one that
// is refused, which is gc's own order: dumpasmhdr runs after the package
// type-checks and after every error is reported. A header written beside a
// refusal would be read by an assembler run the failed build never makes.
func writeAsmHdr(cfg *Config, pkg *types2.Package, files []*syntax.File, info *types2.Info) error {
	if cfg.AsmHdr == "" {
		return nil
	}
	data := AsmHdr(pkg, files, info, types2.SizesFor("gc", TargetArch))
	if err := os.WriteFile(cfg.AsmHdr, data, 0o666); err != nil {
		return fmt.Errorf("-asmhdr: %v", err)
	}
	return nil
}
