// Copyright 2026 The golang.design Initiative Authors.
// All rights reserved. Use of this source code is governed by
// a BSD-style license that can be found in the LICENSE file.

package driver

import (
	"os"
	"os/exec"
	"path/filepath"
	goruntime "runtime"
	"strings"
	"testing"

	"golang.design/x/nanogo/types2"
)

// asmHdrCorpus is every package the bootstrap closure refuses for assembly.
//
// The eight are the ones specs/047-abi-wrappers.md measured, and the set is
// fixed rather than sampled because the header is compared byte for byte: a
// writer that spells a constant differently from gc produces an assembly file
// that assembles to different code and nothing reports it. runtime is in the
// list for a second reason. Its header is 2622 lines over 176 source files,
// which is the only package with enough declarations to expose an ordering
// divergence between nanogo's walk over the parsed files and gc's walk over
// typecheck.Target.AsmHdrDecls.
var asmHdrCorpus = []string{
	"internal/abi",
	"internal/bytealg",
	"internal/chacha8rand",
	"internal/cpu",
	"internal/runtime/atomic",
	"internal/runtime/maps",
	"internal/runtime/sys",
	"runtime",
}

// TestAsmHdrMatchesGc compares nanogo's -asmhdr output against gc's.
//
// This is the whole gate on the header. specs/047-abi-wrappers.md names two
// details a writer gets wrong, and both are silent: the header names the
// package by its name and not its path, and a constant is written with
// constant.Value.ExactString, so a string constant is Go-quoted and a
// 256-byte table reaches the assembler verbatim. Neither is visible in a test
// that checks the header parses.
func TestAsmHdrMatchesGc(t *testing.T) {
	arm64Only(t)
	needGoCommand(t)
	goroot := stdSourceRoot(t)
	work := t.TempDir()

	for _, path := range asmHdrCorpus {
		t.Run(path, func(t *testing.T) {
			pkg := loadStdPackage(t, goroot, work, path)
			want := gcAsmHdr(t, work, pkg)
			got := nanogoAsmHdr(t, pkg)
			if string(got) == want {
				return
			}
			t.Errorf("the header differs from gc's for %s\n%s", path,
				firstDifference(want, string(got)))
		})
	}
}

// TestAsmHdrIsWrittenForAPackageThatOwesNoWrapper checks the file reaches
// disk, which is what the second assembler run reads.
//
// The header must be written even for a package that owes no wrapper. It is
// the input to that run and the assembler fails to find the #define
// otherwise, so a compile that decided the package needed no header would
// break the build a step later with a message about an undefined symbol.
func TestAsmHdrIsWrittenForAPackageThatOwesNoWrapper(t *testing.T) {
	arm64Only(t)
	needGoCommand(t)
	dir := t.TempDir()
	hdr := filepath.Join(dir, "go_asm.h")
	src := "package main\n\nconst K = 7\n\ntype S struct {\n\tA int32\n\tB [3]byte\n\tC int64\n}\n"
	if _, err := compileSource(t, src, func(c *Config) { c.AsmHdr = hdr }); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	data, err := os.ReadFile(hdr)
	if err != nil {
		t.Fatalf("the header was not written: %v", err)
	}
	// Checked against gc for the same source. The order is the source's, so
	// the constant comes first, and the [3]byte at offset 4 leaves the int64
	// at 8 rather than at 7.
	want := "// generated by compile -asmhdr from package main\n\n" +
		"#define const_K 7\n" +
		"#define S__size 16\n#define S_A 0\n#define S_B 4\n#define S_C 8\n"
	if string(data) != want {
		t.Errorf("header is\n%s\nwant\n%s", data, want)
	}
}

// stdSourceRoot is GOROOT's src directory, or a skip.
//
// The oracle is the installed toolchain's own source and its own compiler, so
// a machine without them proves nothing rather than failing. rtsym gates its
// runtime symbol table the same way, and for the same reason: the corpus is a
// property of the machine and not of nanogo.
func stdSourceRoot(t *testing.T) string {
	t.Helper()
	root := filepath.Join(goruntime.GOROOT(), "src")
	if _, err := os.Stat(filepath.Join(root, "internal", "abi")); err != nil {
		if os.Getenv("NANOGO_REQUIRE_CORPUS") == "1" {
			t.Fatal("NANOGO_REQUIRE_CORPUS=1 and the standard library source under GOROOT could not be read")
		}
		t.Skip("no standard library source under GOROOT")
	}
	return root
}

// stdPackage is one standard library package, as the go command describes it.
type stdPackage struct {
	Path      string   // the import path
	Dir       string   // the package directory
	Files     []string // the Go files, absolute, in the order the go command lists them
	SFiles    []string // the assembly files, in the order the go command lists them
	ImportCfg string   // the file holding the packagefile lines its imports need
	SymABIs   string   // the file cmd/asm -gensymabis wrote, empty when there is no assembly
	Include   string   // the directory holding the empty go_asm.h of the first pass
}

// loadStdPackage asks the go command for a package's files and builds the
// importcfg both compilers read.
//
// The export files come from go list rather than from a build of nanogo's
// own, because the oracle has to be gc's answer for gc's inputs.
func loadStdPackage(t *testing.T, goroot, work, path string) stdPackage {
	t.Helper()
	out := goList(t, goroot, "{{.Dir}}\n{{range .GoFiles}}go {{.}}\n{{end}}{{range .SFiles}}s {{.}}\n{{end}}", path)
	lines := strings.Split(strings.TrimRight(out, "\n"), "\n")
	if len(lines) < 1 {
		t.Fatalf("go list gave no directory for %s", path)
	}
	p := stdPackage{Path: path, Dir: lines[0]}
	for _, l := range lines[1:] {
		kind, name, _ := strings.Cut(l, " ")
		switch kind {
		case "go":
			p.Files = append(p.Files, filepath.Join(p.Dir, name))
		case "s":
			p.SFiles = append(p.SFiles, name)
		}
	}

	var cfg strings.Builder
	deps := goList(t, goroot, "{{.ImportPath}} {{.Export}}\n", "-deps", "-export", path)
	for _, line := range strings.Split(deps, "\n") {
		fields := strings.Fields(line)
		if len(fields) != 2 || fields[0] == path {
			continue
		}
		cfg.WriteString("packagefile " + fields[0] + "=" + fields[1] + "\n")
	}
	name := strings.ReplaceAll(path, "/", "_")
	p.ImportCfg = filepath.Join(work, name+".importcfg")
	if err := os.WriteFile(p.ImportCfg, []byte(cfg.String()), 0o600); err != nil {
		t.Fatal(err)
	}
	gensymabis(t, work, name, &p)
	return p
}

// gensymabis runs the assembler's first pass, the way the go command does.
//
// The two passes are not optional and the order matters: the go command writes
// an empty go_asm.h, runs cmd/asm -gensymabis against it to produce the
// symabis file, and only then runs the compiler with -symabis and -asmhdr.
// Without -symabis gc refuses runtime outright, because
// internal/abi.FuncPCABI0 checks the named function's definition ABI against
// the symabis defs and eleven call sites in runtime name an ABI0 assembly
// function.
func gensymabis(t *testing.T, work, name string, p *stdPackage) {
	t.Helper()
	if len(p.SFiles) == 0 {
		return
	}
	p.Include = filepath.Join(work, name+".inc")
	if err := os.MkdirAll(p.Include, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(p.Include, "go_asm.h"), nil, 0o600); err != nil {
		t.Fatal(err)
	}
	p.SymABIs = filepath.Join(work, name+".symabis")
	args := []string{"tool", "asm",
		"-p", p.Path,
		"-I", p.Include + string(filepath.Separator),
		"-I", filepath.Join(goruntime.GOROOT(), "pkg", "include"),
		"-D", "GOOS_darwin", "-D", "GOARCH_" + TargetArch,
		"-shared", "-std", "-gensymabis",
		"-o", p.SymABIs,
	}
	for _, f := range p.SFiles {
		args = append(args, filepath.Join(p.Dir, f))
	}
	cmd := exec.Command("go", args...)
	cmd.Dir = p.Dir
	cmd.Env = append(os.Environ(),
		"GOOS=darwin", "GOARCH="+TargetArch, "CGO_ENABLED=0",
		"GOTMPDIR="+t.TempDir(), "TMPDIR="+t.TempDir())
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go tool asm -gensymabis %s: %v\n%s", p.Path, err, out)
	}
}

// goList runs go list for the target the header is written for.
func goList(t *testing.T, goroot, format string, args ...string) string {
	t.Helper()
	argv := append([]string{"list", "-f", format}, args...)
	cmd := exec.Command("go", argv...)
	cmd.Dir = goroot
	cmd.Env = append(os.Environ(),
		"GOOS=darwin", "GOARCH="+TargetArch, "CGO_ENABLED=0",
		"GOTMPDIR="+t.TempDir(), "TMPDIR="+t.TempDir())
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("go list %v: %v", argv, err)
	}
	return string(out)
}

// gcAsmHdr is the oracle: the header the real compiler writes.
//
// The flags are the ones a real build sends, read out of go build -x for
// these packages: -p, -lang, -std, -shared, -nolocalimports, -importcfg and
// -asmhdr. -o is a file in the work directory rather than /dev/null, because
// gc writes the object before it writes the header.
func gcAsmHdr(t *testing.T, work string, p stdPackage) string {
	t.Helper()
	name := strings.ReplaceAll(p.Path, "/", "_")
	hdr := filepath.Join(work, name+".gc.h")
	args := []string{"tool", "compile",
		"-o", filepath.Join(work, name+".o"),
		"-p", p.Path,
		"-lang=go1.27",
		"-std", "-shared", "-nolocalimports",
		"-importcfg", p.ImportCfg,
		"-asmhdr", hdr,
	}
	if p.SymABIs != "" {
		args = append(args, "-symabis", p.SymABIs)
	}
	cmd := exec.Command("go", append(args, p.Files...)...)
	cmd.Env = append(os.Environ(),
		"GOOS=darwin", "GOARCH="+TargetArch, "CGO_ENABLED=0",
		"GOTMPDIR="+t.TempDir(), "TMPDIR="+t.TempDir())
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go tool compile -asmhdr %s: %v\n%s", p.Path, err, out)
	}
	data, err := os.ReadFile(hdr)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// nanogoAsmHdr runs nanogo's front end over the same files and returns what
// [AsmHdr] writes.
//
// It goes through the front end rather than through [Compile], because
// [checkSupported] refuses package runtime by name and the header writer is
// not what that refusal is about. This is also the shape the writer has to
// have: everything it needs is the parsed files and the checker's record.
func nanogoAsmHdr(t *testing.T, p stdPackage) []byte {
	t.Helper()
	cfg := &Config{Package: p.Path, Lang: "go1.27", Std: true, Files: p.Files, GOARCH: TargetArch}
	var err error
	if cfg.ImportCfg, err = ReadImportCfg(p.ImportCfg); err != nil {
		t.Fatal(err)
	}
	files, fset, _, err := parseFiles(cfg)
	if err != nil {
		t.Fatalf("parsing %s: %v", p.Path, err)
	}
	pkg, info, err := checkFiles(cfg, newImporter(cfg), files, fset)
	if err != nil {
		t.Fatalf("checking %s: %v", p.Path, err)
	}
	return AsmHdr(pkg, files, info, types2.SizesFor("gc", TargetArch))
}

// firstDifference reports the first line the two headers disagree on, with
// the lines around it.
//
// A diff of 2622 lines is unreadable and the failure is always one line, so
// the message names the line number and prints both.
func firstDifference(want, got string) string {
	w, g := strings.Split(want, "\n"), strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		lw, lg := "", ""
		if i < len(w) {
			lw = w[i]
		}
		if i < len(g) {
			lg = g[i]
		}
		if lw == lg {
			continue
		}
		var b strings.Builder
		for j := max(0, i-3); j < i; j++ {
			b.WriteString("  " + w[j] + "\n")
		}
		b.WriteString("gc line " + itoa(i+1) + ": " + lw + "\n")
		b.WriteString("nanogo:       " + lg + "\n")
		return b.String()
	}
	return "the headers hold the same lines"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}
